export const text = {
  INCOME: 'Total Income',
  EXPENSE: 'Total Expense',
  STATUS: 'Status',
  NO_DATA_FOUND: 'No data found',
  ERROR_FETCHING: 'Error fetching data',
  DATE: 'Date',
  DESCRIPTION: 'Description',
  AMOUNT: 'Amount',
  TYPE: 'Type',
  BOOKINGS: 'Bookings',
  BOOKING_UPDATED: 'Booking updated successfully',
  BOOKING_ADDED: 'Booking added successfully',
  EDIT_BOOKING: 'Edit Booking',
  ADD_BOOKING: 'Add Booking',
  CUSTOMER: 'Customer',
  SELECT_CUSTOMER: 'Select Customer',
  VEHICLE: 'Vehicle',
  SELECT_VEHICLE: 'Select Vehicle',
  DRIVER: 'Driver',
  SELECT_DRIVER: 'Select Driver',
  TRIP_TYPE: 'Trip Type',
  SINGLE_TRIP: 'Single Trip',
  ROUND_TRIP: 'Round Trip',
  TRIP_START_LOC: 'Trip Start Location',
  TRIP_END_LOC: ' Trip End Location',
  TOTAL_KM: 'Approx Total KM',
  TRIP_START_DATE: 'Trip Start Date',
  TRIP_END_DATE: 'Trip End Date',
  TOTAL_AMOUNT: 'Total Amount',
  TRIP_STATUS: 'Trip Status',
  YET_TO_START: 'Yet to Start',
  ONGOING: 'Ongoing',
  COMPLETED: 'Completed',
  CANCELLED: 'Cancelled',
  UPDATE_BOOKING: 'Update Booking',
  CUSTOMER_REQUIRED: 'Customer is required',
  DRIVER_REQUIRED: 'Driver id required',
  VEHICLE_REQUIRED: 'Vehicle is required',
  START_LOC_REQUIRED: 'Trip Start Location is required',
  END_LOC_REQUIRED: 'Trip End Location is required',
  START_LOC: 'Enter Start Location',
  END_LOC: 'Enter End Location',
  KM_REQUIRED: 'Total KM is required',
  START_DATE_REQUIRED: 'Trip Start Date & Time is required',
  END_DATE_REQUIRED: 'Trip End Date & Time is required',
  END_DATE_AFTER_START: 'End Date must be after Start Date',
  GREATER_THAN_0: 'Must be greater than 0',
  CANNOT_EXCEED: 'Cannot exceed 100,000'
};
