export const text = {
  S_NO: 'S.No',
  NAME: 'Name',
  EMAIL: 'Email',
  PHONE: 'Phone No',
  STATUS: 'Status',
  DATE: 'Date',
  ACTION: 'Action',
  DESCRIPTION: 'Description',
  AMOUNT: 'Amount',
  CREATED_AT: 'Created At',
  TYPE: 'Type',
  SELECT_TYPE: 'Select Type',
  MOBILE: 'Mobile',
  AGE: 'Age',
  ADDRESS: 'Address',
  LICENSE_NO: 'License No',
  LICENSE_EXP_DATE: 'License Expiry Date',
  PHOTO: 'Photo',
  IMAGE: 'Image',
  DOCUMENT: 'Document',
  NOTES: 'Reference/Notes',
  DATE_OF_JOINING: 'Date of Joining',
  TOTAL_EXP: 'Total Experience',
  FILL_DATE: 'Fill Date',
  QUANTITY: 'Quantity',
  ODOMETER_READING: 'Odometer Reading',
  COMMENTS: 'Comments',
  PARTS: 'Parts Name',
  QTY: 'Qty',
  SERVICE_DETAILS: 'Service Details',
  VENDOR_NAME: 'Vendor Name',
  TOTAL_COST: 'Total Cost',
  RES_NO: 'Registration Number',
  MODEL: ' Model',
  RES_EXP_DATE: 'Registration Expiry Date',
  COLOR: 'Vehicle Color',
  MANUFACTURED_BY: ' Manufactured By',
  ENGINE_NO: 'Engine No',
  CHASIS_NO: ' Chassis No',
  GPS_API: 'GPS API URL',
  API_USERNAME: 'API Username',
  API_PASS: 'API Password',
  GPS_DETAILS: 'GPS API Details(Feed GPS Data)',
  DISTANCE: 'Distance',
  TRIP_START_LOC: 'Trip Start Location',
  TRIP_END_LOC: 'Trip End Location',
  TRIP_START_PIN: 'Trip Start Pincode',
  TRIP_END_PIN: 'Trip End Pincode',
  TOTAL_KM: 'Approx Total KM',
  START_DATE: 'Start Date',
  END_DATE: 'End Date',
  OVERVIEW: 'Overview',
  ADD_TRIP_EXPENSE: 'Add Trip Expense',
  ADD_EXPENSE: 'Add Expense',
  TRACKING_URL: ' Tracking URL',
  TRIP_EXPENSE: 'Trip Expense',
  GENERATE_INVOICE: ' Generate Invoice',
  SHARE_TO_CUSTOMER: 'Share to Customer',
  EXCESS: 'Excess',
  STOCK: 'Stock',
  CREATED_DATE: 'Created Date',
  MODIFIED_DATE: 'Modified Date',
  GEOFENCE: 'Geofence',
  NOTIFICATIONS: 'Notifications',
  BASIC_INFO: 'Basic Info',
  EXPIRY_DATE_FUTURE: 'EXpiry date must be in future.',
  SELECT_START_END_DATE: 'Please select both start and end dates',

  //Payment
  AMT_ERROR: 'Paid amount cannot exceed total amount',
  SAVE_PAYMENT: 'Save Payment',
  MAKE_PAYMENT: 'Make Payment',
  TOTAL_AMOUNT: 'Total Amount',
  PENDING_AMOUNT: 'Pending Amount',
  PAID_AMOUNT: 'Paid Amount',
  PAID_ON: 'Paid On',
  PAYEMNT_ACTIVITY: ' Payment Activity',
  ADD_PAYMENT: ' Add Payment',
  PAYMENT_ADDED: 'Payment added successfully',
  PAYMENT_DELETED: 'Payment deleted successfully',
  PAYMENT_INFO: 'Payment Information',
  INVOICE: 'INVOICE',
  INV_NO: 'Invoice No',
  DOWNLOAD: 'Download',

  //Bookings
  BOOKINGS: 'Bookings',
  BOOKING_STATUS_UPDATED: 'Booking status updated successfully',
  BOOKING_DELETED: 'Booking deleted successfully',
  BOOKING_UPDATED: 'Booking updated successfully',
  BOOKING_ADDED: 'Booking added successfully',
  EDIT_BOOKING: 'Edit Booking',
  ADD_BOOKING: 'Add Booking',
  UPDATE_BOOKING: 'Update Booking',
  BOOKING_DETAILS: 'Booking Details',
  BOOKING_ID: 'Booking ID',
  BOOKING_EXP_ADDED: 'Booking expense added successfully',
  BOOKING_EXP_DELETED: 'Booking expense deleted successfully',

  //Customer
  CUSTOMER: 'Customer',
  CUSTOMER_DELETED: 'Customer deleted successfully',
  CUSTOMER_UPDATED: 'Customer updated successfully',
  CUSTOMER_ADDED: 'Customer added successfully',
  EDIT_CUSTOMER: 'Edit Customer',
  ADD_CUSTOMER: 'Add Customer',
  VIEW_CUSTOMER: 'View Customer',
  SELECT_CUSTOMER: 'Select Customer',
  CUSTOMER_INFO: 'Customer Info',
  CUSTOMER_MGNT: 'Customer Management',

  //Driver
  DRIVER: 'Driver',
  DRIVER_NAME: 'Driver Name',
  DRIVER_DELETED: 'Driver deleted successfully',
  DRIVER_UPDATED: 'Driver updated successfully',
  DRIVER_ADDED: 'Driver added successfully',
  EDIT_DRIVER: 'Edit Driver',
  ADD_DRIVER: 'Add Driver',
  VIEW_DRIVER: 'View Driver',
  SELECT_DRIVER: 'Select Driver',
  DRIVER_INFO: 'Driver Info',
  DRIVER_MGNT: 'Driver Management',
  ALL_DRIVER: 'All Drivers',

  //Fuel
  FUEL_UPDATED: 'Fuel updated successfully',
  FUEL_ADDED: 'Fuel added successfully',
  FUEL_DELETED: 'Fuel deleted successfully',
  FUEL: 'Fuel',
  UPDATE_FUEL: 'Update Fuel',
  EDIT_FUEL: 'Edit Fuel',
  ADD_FUEL: 'Add Fuel',
  FUEL_MGNT: 'Fuel Management',
  FUEL_FILL_BY: 'Fuel Filled By',

  //Maintenance
  MAINTENANCE_ADDED: 'Maintenance added successfully',
  MAINTENANCE_UPDATED: 'Maintenance updated successfully',
  MAINTENANCE_DELETED: 'Maintenance deleted successfully',
  ADD_MAINTENANCE: 'Add Maintenance',
  MAINTENANCE: 'Maintenance',
  MAINTENANCE_RECORDS: 'Maintenance Records',

  //Vehicle
  VEHICLE: 'Vehicles',
  SELECT_VEHICLE: 'Select Vehicle',
  VEHICLE_UPDATED: 'Vehicle updated successfully',
  VEHICLE_ADDED: 'Vehicle added successfully',
  VEHICLE_DELETED: 'Vehicle deleted successfully',
  EDIT_VEHICLE: 'Edit Vehicle',
  ADD_VEHICLE: 'Add Vehicle',
  VEHICLE_NAME: ' Vehicle Name',
  VEHICLE_INFO: 'Vehicle Info',
  VEHICLE_DETAILS: 'Vehicle Details',
  VEHICLE_MNGT: 'Vehicle Management',
  ALL_VEHICLE: 'All Vehicles',
  VEHICLE_TYPE: ' Vehicle Type',
  SELECT_VEHICLE_TYPE: 'Select Vehicle Type',
  CAR: 'CAR',
  BUS: 'BUS',
  TAXI: 'TAXI',
  MOTORCYCLE: 'MOTORCYCLE',
  TRUCK: 'TRUCK',
  BICYCLE: 'BICYCLE',

  //User
  USER: 'User',
  ADD_USER: 'Add User',
  EDIT_USER: 'Edit User',
  VIEW_USER: 'View User',
  USER_LIST: 'Users List',
  USER_ADDED: 'User added successfully',
  USER_UPDATED: 'User updated successfully',
  SAVE_PERMISSIONS: 'Save Permissions',
  USER_PERMISSION: 'User Permission',
  PERMISSION_ADDED: 'Permissions added successfully',

  //Common
  CANCEL: ' Cancel',
  UPDATE: 'Update',
  EDIT: 'Edit',
  ADD: 'Add',

  //Income & Expense
  INC_EXP_UPDATED: 'Income expense updated successfully',
  INC_EXP_ADDED: 'Income expense added successfully',
  INC_EXP_DELETED: 'Income expense deleted successfully',
  INCOME_EXPENSE: 'Income & Expense',
  TOTAL_INCOME: 'Total Income',
  TOTAL_EXPENSE: 'Total Expense',
  INCOME: 'Income',
  EXPENSE: 'Expense',

  //Parts
  PART: 'Part',
  PARTS_ADDED: 'Parts inventory added successfully!',
  PARTS_UPDATED: 'Parts inventory updated successfully!',
  PARTS_DELETED: 'Parts inventory deleted successfully!',
  PARTS_INVENTORY: 'Parts Inventory',

  //Reminder
  REM_ADDED: 'Reminder added successfuly!',
  REM_DELETED: 'Reminder deleted successfully',
  MESSAGE: 'Message',
  REM: 'Reminder',
  REM_INFO: 'Reminder Info',
  ADD_REM: 'Add Reminder',

  //Vehicle Group
  VEHICLE_GROUP: '  Vehicle Group',
  SELECT_GROUP: 'Select Vehicle Group',
  GROUP_UPDATED: 'Vehicle group updated succesfully!',
  GROUP_ADDED: 'Vehicle group added successfully!',
  GROUP_DELETED: 'Vehicle group deleted successfully!',
  GROUP: 'Group',

  //Reports
  REPORTS: 'Reports',
  GENERATE_REPORT: ' Generate Report',
  UPDATE_STATUS: 'Update Status',
  FROM_TO: 'From To',
  FROM: 'From',
  TO: 'To',
  BOOKING_DATE: 'Booking Date',
  CALENDAR: 'Vehicle Calendar',

  //Status
  YET_TO_START: 'Yet to Start',
  ONGOING: 'Ongoing',
  COMPLETED: 'Completed',
  CANCELLED: 'Cancelled',
  PENDING: 'Pending',
  IN_PROGRESS: 'In Progress',
  ACTIVE: 'Active',
  INACTIVE: 'Inactive',
  TRIP_TYPE: 'Trip Type',
  SINGLE_TRIP: 'Single Trip',
  ROUND_TRIP: 'Round Trip',

  //Errors & Validation
  NO_DATA_FOUND: 'No data found',
  NO_DATE_AVAILABLE: 'No data available',
  ERROR_FETCHING: 'Error fetching data',
  ERROR_UPDATING: 'Error updating data',
  INVALID_FORMAT: 'Invalid data format',
  REQUIRED: 'Field is required',
  ERROR: 'Something went wrong!',

  //MIN & MAX
  END_DATE_AFTER_START: 'End Date must be after Start Date',
  GREATER_THAN_0: 'Must be greater than 0',
  CANNOT_EXCEED: 'Cannot exceed 100,000',
  MIN_3_CHAR: 'At least 3 characters required',
  MIN_4_CHAR: 'At least 4 characters required',
  MIN_5_CHAR: 'At least 5 characters required',
  MIN_6_CHAR: 'At least 6 characters required',
  MAX_12_CHAR: 'Max 12 characters allowed',
  MAX_14_CHAR: 'Max 14 characters allowed',
  MAX_17_CHAR: 'Max 17 characters allowed',
  MAX_20_CHAR: 'Max 20 characters allowed',
  MAX_30_CHAR: 'Max 30 characters allowed',
  MAX_50_CHAR: 'Max 50 characters allowed',
  MAX_100_CHAR: 'Max 100 characters allowed',
  MAX_200_CHAR: 'Max 200 characters allowed',
  MIN_18_AGE: 'Age must be at least 18',
  MAX_50_AGE: 'Age must be below 50',
  MIN_1_EXP: 'At least 1 year of experience',
  MAX_40_EXP: 'Max 40 years of experience allowed',
  MIN_10_DIGIT: 'Must be at least 10 digits',
  MAX_12_DIGIT: 'Cannot exceed 12 digits',
  MIN_1_STOCK: 'At least 1 stock is required',
  MAX_1000_STOCK: 'Stock must be below 1000',
  ALPHABETS_ONLY: 'Only alphabets are allowed (A-Z, a-z)',
  NUMBERS_ONLY: 'Only numbers are allowed',
  ALPHA_NUM: 'Only alphabets and numbers are allowed',
  SELECT_ONE: 'Please select at least one valid part',
  SEARCH: 'Search...',
  LOGOUT_SUCCESS: 'Logged out successfully!',
  LOGIN_SUCCESS: 'Logged in successfully!',
  LOGIN: 'Log In',
  PASSWORD: 'Password',
  EMAIL_USERNAME: 'Email Address',

  USER_ACCOUNT: 'User Account',
  CURRENCY_UPDATE: 'Currency updated successfully',
  CONTACT_INFO: 'Contact Information',
  LOC: 'Location',
  ABOUT_US: 'About Us',
  CURRENCY_SETTINGS: 'Currency Settings',
  SELECT_CURRENCY: 'Select Currency',
  SAVE_CURRENCY: 'Save Currency',
  CURRENCY_CODE: 'Currency Code',
  CURRENCY_SYMBOL: 'Currency Symbol',
  PROFILE: 'Profile',
  SETTINGS: 'Settings',
  LOGOUT: 'Logout',
  VIEW: '  View',
  DRIVER_PHOTO: 'Driver Photo',
  DRIVER_DOC: 'Driver Document',

  AVAILABLE: 'Available',
  TODAY: 'Today',
  VEHICLE_AVAIL: 'Vehicle Availability',
  WELCOME_FLEET: 'Welcome aboard your Fleet Management Hub',
  MONTHLY_INC_EXP: 'Monthly Income/Expense',
  TOTAL_VEHICLES: 'Total Vehicles',
  TOTAL_DRIVERS: 'Total Drivers',
  TOTAL_CUSTOMERS: 'Total Customers',
  TOTAL_TRIPS: 'Today Trips',
  CUS_ADDED_MONTH: 'customers added this month',
  BOOKINGS_THIS_MONTH: 'bookings this month',
  DRIVER_JOINED_THIS_MONTH: 'drivers joined this month',
  VEHICLES_ADDED_THIS_MONTH: 'vehicles added this month',
  NO_REM: 'No reminders found.',
  EDIT_PROFILE: 'Edit Profile',
  SAVE_PROFILE: 'Save Profile',
  CHANGE_PASSWORD: 'Change Password',
  UPDATE_CURRENCY: 'Update Currency',
  PASSWORDS_DO_NOT_MATCH: 'Passwords do not match',
  PASSWORD_UPDATED_SUCCESSFULLY: 'Password updated successfully',
  OLD_PASSWORD: 'Old Password',
  NEW_PASSWORD: 'New Password',
  CONFIRM_PASSWORD: 'Confirm Password',
  UPDATE_PASSWORD: 'Update Password',
  DRIVER_ALERT: 'Driver Alert',
  VEHICLE_BREAKDOWN: 'Vehicle Breakdown',
  DRIVING_LICENSE: 'Driving License',
};
